const KEY='micontrol_pro_v2';
const defaultData={config:{owner:'MiControl PRO',currency:'$',pin:'1234',theme:'dark'},accounts:[{id:crypto.randomUUID(),name:'Efectivo',balance:0},{id:crypto.randomUUID(),name:'Banco',balance:0}],movements:[],goals:[]};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||defaultData;
const $=id=>document.getElementById(id); const money=n=>`${db.config.currency} ${Number(n||0).toFixed(2)}`;
function save(){localStorage.setItem(KEY,JSON.stringify(db));render()}
function total(type){return db.movements.filter(m=>m.type===type).reduce((a,b)=>a+Number(b.amount),0)}
function balance(){return db.accounts.reduce((a,b)=>a+Number(b.balance),0)}
function switchTab(name){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===name))}
function render(){document.body.classList.toggle('light',db.config.theme==='light');$('themeBtn').textContent=db.config.theme==='light'?'🌙':'☀️';$('ownerName').textContent=db.config.owner;$('cfgOwner').value=db.config.owner;$('cfgCurrency').value=db.config.currency;$('balanceTotal').textContent=money(balance());$('totalIngresos').textContent=money(total('income'));$('totalGastos').textContent=money(total('expense'));$('totalAhorro').textContent=money(db.goals.reduce((a,g)=>a+Number(g.saved||0),0));let income=total('income'), exp=total('expense');let h=income?Math.max(0,Math.min(100,Math.round(((income-exp)/income)*100))):0;$('healthScore').textContent=h+'%';$('healthText').textContent='Salud financiera '+h+'%';renderMovements();renderAccounts();renderGoals();renderReports();}
function renderMovements(){let q=($('searchMov').value||'').toLowerCase(),f=$('filterType').value;let list=db.movements.filter(m=>(f==='all'||m.type===f)&&(`${m.desc} ${m.category}`.toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date));$('movList').innerHTML=list.length?list.map(m=>`<div class="item"><div><b>${m.desc||m.category}</b><br><small>${m.date} · ${m.category} · ${accountName(m.accountId)}</small></div><div><div class="amount ${m.type==='income'?'plus':'minus'}">${m.type==='income'?'+':'-'} ${money(m.amount)}</div><button class="secondary" onclick="delMovement('${m.id}')">Eliminar</button></div></div>`).join(''):'<p class="muted">Sin movimientos todavía.</p>';}
function renderAccounts(){let opts=db.accounts.map(a=>`<option value="${a.id}">${a.name}</option>`).join('');$('mAccount').innerHTML=opts;$('accountList').innerHTML=db.accounts.map(a=>`<div class="item"><div><b>${a.name}</b><br><small>Saldo disponible</small></div><div><div class="amount plus">${money(a.balance)}</div><button class="secondary" onclick="delAccount('${a.id}')">Eliminar</button></div></div>`).join('')||'<p class="muted">Sin cuentas.</p>';}
function renderGoals(){$('goalList').innerHTML=db.goals.map(g=>{let pct=Math.min(100,Math.round((Number(g.saved||0)/Number(g.target||1))*100));return `<div class="item"><div style="width:100%"><b>${g.name}</b><br><small>${money(g.saved)} de ${money(g.target)} · ${pct}%</small><div class="progress"><div class="bar" style="width:${pct}%"></div></div></div><button class="secondary" onclick="delGoal('${g.id}')">Eliminar</button></div>`}).join('')||'<p class="muted">Sin metas registradas.</p>';}
function renderReports(){let month=new Date().toISOString().slice(0,7);let monthMov=db.movements.filter(m=>m.date.startsWith(month));let mb=monthMov.reduce((a,m)=>a+(m.type==='income'?Number(m.amount):-Number(m.amount)),0);$('monthBalance').textContent=money(mb);let cats={};monthMov.filter(m=>m.type==='expense').forEach(m=>cats[m.category]=(cats[m.category]||0)+Number(m.amount));let top=Object.entries(cats).sort((a,b)=>b[1]-a[1])[0];$('topCategory').textContent=top?`${top[0]} ${money(top[1])}`:'-';drawChart(cats)}
function drawChart(cats){let c=$('chart'),ctx=c.getContext('2d'),w=c.width=c.offsetWidth*2,h=c.height=320;ctx.clearRect(0,0,w,h);let entries=Object.entries(cats);if(!entries.length){ctx.fillStyle=getComputedStyle(document.body).getPropertyValue('--muted');ctx.font='28px Arial';ctx.fillText('Sin datos de gastos este mes',30,170);return}let max=Math.max(...entries.map(e=>e[1]));entries.slice(0,6).forEach((e,i)=>{let y=35+i*45,bw=(w-220)*(e[1]/max);ctx.fillStyle='#38bdf8';ctx.fillRect(180,y,bw,26);ctx.fillStyle=getComputedStyle(document.body).getPropertyValue('--text');ctx.font='22px Arial';ctx.fillText(e[0].slice(0,12),20,y+22);ctx.fillText(money(e[1]),190+bw,y+22)})}
function accountName(id){return (db.accounts.find(a=>a.id===id)||{}).name||'Sin cuenta'}
function delMovement(id){let m=db.movements.find(x=>x.id===id);if(m){let a=db.accounts.find(x=>x.id===m.accountId);if(a)a.balance+=m.type==='income'?-Number(m.amount):Number(m.amount)}db.movements=db.movements.filter(m=>m.id!==id);save()}
function delAccount(id){if(db.accounts.length<=1)return alert('Debes dejar al menos una cuenta.');db.accounts=db.accounts.filter(a=>a.id!==id);save()}
function delGoal(id){db.goals=db.goals.filter(g=>g.id!==id);save()}
$('unlockBtn').onclick=()=>{if($('pinInput').value===db.config.pin){$('lock').classList.add('hidden');$('app').classList.remove('hidden');render()}else alert('PIN incorrecto')};$('lockBtn').onclick=()=>{$('app').classList.add('hidden');$('lock').classList.remove('hidden');$('pinInput').value=''};$('themeBtn').onclick=()=>{db.config.theme=db.config.theme==='light'?'dark':'light';save()};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('addMovementBtn').onclick=()=>{$('mDate').value=new Date().toISOString().slice(0,10);$('movementModal').showModal()};$('addAccountBtn').onclick=()=>$('accountModal').showModal();$('addGoalBtn').onclick=()=>$('goalModal').showModal();$('saveMovement').onclick=e=>{e.preventDefault();let amount=Number($('mAmount').value);if(!amount)return alert('Coloca un monto.');let m={id:crypto.randomUUID(),type:$('mType').value,amount,category:$('mCategory').value||'General',desc:$('mDesc').value||'Movimiento',date:$('mDate').value||new Date().toISOString().slice(0,10),accountId:$('mAccount').value};db.movements.push(m);let a=db.accounts.find(x=>x.id===m.accountId);if(a)a.balance+=m.type==='income'?amount:-amount;['mAmount','mCategory','mDesc'].forEach(id=>$(id).value='');$('movementModal').close();save()};$('saveAccount').onclick=e=>{e.preventDefault();db.accounts.push({id:crypto.randomUUID(),name:$('aName').value||'Cuenta',balance:Number($('aBalance').value||0)});$('aName').value='';$('aBalance').value='';$('accountModal').close();save()};$('saveGoal').onclick=e=>{e.preventDefault();db.goals.push({id:crypto.randomUUID(),name:$('gName').value||'Meta',target:Number($('gTarget').value||0),saved:Number($('gSaved').value||0)});$('gName').value='';$('gTarget').value='';$('gSaved').value='';$('goalModal').close();save()};$('saveConfig').onclick=()=>{db.config.owner=$('cfgOwner').value||'MiControl PRO';db.config.currency=$('cfgCurrency').value;if($('cfgPin').value)db.config.pin=$('cfgPin').value;$('cfgPin').value='';save();alert('Configuración guardada')};$('searchMov').oninput=renderMovements;$('filterType').onchange=renderMovements;
$('exportCsv').onclick=()=>{let rows=[['Fecha','Tipo','Monto','Categoría','Descripción','Cuenta'],...db.movements.map(m=>[m.date,m.type,m.amount,m.category,m.desc,accountName(m.accountId)])];download('micontrol_movimientos.csv',rows.map(r=>r.join(';')).join('\n'),'text/csv')};$('backupBtn').onclick=()=>download('micontrol_respaldo.json',JSON.stringify(db,null,2),'application/json');$('restoreInput').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);save();alert('Respaldo restaurado')}catch{alert('Archivo inválido')}};r.readAsText(f)};$('exportPdf').onclick=()=>{let html=`<h1>Reporte MiControl PRO</h1><p>Balance: ${money(balance())}</p><p>Ingresos: ${money(total('income'))}</p><p>Gastos: ${money(total('expense'))}</p>`;let w=window.open('','_blank');w.document.write(html);w.print()};function download(name,content,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click()} if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});render();
